Using numpy is a good way of working with arrays in new and more useful ways. This is especially true when matrix operations are required. Let us proceed with this guide to numpy.

In [ ]:
import numpy as np

Let us go about building an array.

In [5]:
a = np.array([2,3,4])
print(a)

[2 3 4]


In [4]:
b = np.array([(1,2,3), (4,5,6)])
print(b)

[[1 2 3]
 [4 5 6]]


The natural question to ask at this stage, is what is the difference between an array and a list? This is a good question!

There are two key differences:

1. An array must contain elements that are all the same type, whereas this is not a requirement in a list. For example, in the above arrays, every element is an int. Compare that to say, the following:

alpha = [3, 'dog'. 4.2]

Here, alpha is a list containing an int, a string, and a float.


2. Arrays are immutable, whereas lists are mutable.




Let us continue with some more examples of how arrays work in a basic sense.

In [20]:
print(a)

[2 3 4]


In [24]:
print(a[0])
print(a[1])
print(a[0] + a[2])

2
3
6


In [26]:
a[1] = 8
print(a)

[2 8 4]


In [27]:
a[0] = 'this is fun!'
print(a)

ValueError: invalid literal for int() with base 10: 'this is fun!'

Let's look at some other quick commands that might be useful to you:

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [29]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [31]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [11]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [32]:
np.arange(10, 30, 5).reshape(2,2)

array([[10, 15],
       [20, 25]])

As you can imagine, this ability to quickly build arrays and reshape them will make wriiting code much faster and easier for you.

Now, let us consider some of the matrix operations:

$A + B = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & a_{22} \end{bmatrix} + \begin{bmatrix} b_{11} & b_{12}\\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} a_{11} + b_{11} & a_{12} + b_{12}\\ a_{21} + b_{21}& a_{22}+b_{22} \end{bmatrix}$ 

$A * B = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & a_{22} \end{bmatrix} * \begin{bmatrix} b_{11} & b_{12}\\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} a_{11} * b_{11} & a_{12} * b_{12}\\ a_{21} * b_{21}& a_{22} * b_{22} \end{bmatrix}$

$A @ B = \begin{bmatrix} a_{11} & a_{12}\\ a_{21} & a_{22} \end{bmatrix} * \begin{bmatrix} b_{11} & b_{12}\\ b_{21} & b_{22} \end{bmatrix} = \begin{bmatrix} a_{11}b_{11}+a_{12}b_{21} & a_{11}b_{12}+a_{12}b_{22}\\ a_{21}b_{12}+a_{22}b_{21}& a_{21}b_{12}+a_{22}b_{22} \end{bmatrix} $



This is a warning! A * B does NOT give standard matrix multiplication. This is the job of A @ B.

In [33]:
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0], [3,4]] )

In [34]:
A + B

array([[3, 1],
       [3, 5]])

In [35]:
A * B

array([[2, 0],
       [0, 4]])

In [36]:
A @ B

array([[5, 4],
       [3, 4]])